application: locatewhereami
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: (.*)/
  static_files: church\1/index.html
  upload: whereami/index.html

- url: /
  static_dir: whereami
