application: churchwebsite
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: (.*)/
  static_files: church\1/home.html
  upload: church/home.html

- url: /
  static_dir: church