runtime: nodejs
vm: true
handlers:
- url: /.*
  script: IGNORED
  secure: always
threadsafe: true
resources:
  cpu: .5
  memory_gb: .4
  disk_size_gb: 10
manual_scaling:
  instances: 1
skip_files:
- ^node_modules$
