runtime: nodejs
vm: true
handlers:
- url: /.*
  script: IGNORED
  secure: always
threadsafe: true
resources:
  cpu: .1
  memory_gb: .1
  disk_size_gb: 10
manual_scaling:
  instances: 1
health_check:
  enable_health_check: True
  check_interval_sec: 60
  timeout_sec: 8
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 4
env_variables:
  NODE_ENV: production
skip_files:
- ^node_modules$
